### ISSUE TITLE
Installed but upon browser network insepction of https site, supported compressible files still compressed as gzip

### ISSUE THREAD

**Issue by yrfu** [Microsoft/IIS.Compression#13]
As per above, this was installed on IIS 8.5 from [iis.net/downloads/microsoft/iis-compression](https://www.iis.net/downloads/microsoft/iis-compression#additionalDownloads) but after installing and iisreset, the files covered by the compression scheme still compressed via gzip.

Application.config shows the compression scheme installed as per installer action but it did not state the desired compression level for static or dynamic. Am I missing something?

I have tried [saucecontrol](https://www.iis.net/downloads/community/2018/02/brotli-compression-scheme-plugin) version of brotli compression scheme but it requires URL rewrite rule on HTTP_ACCEPT_ENCODING to force prefer brotli over gzip. I would like to avoid installing that on assumption that this updated MSFT IIS compression scheme implementation would automagically do the job.

It would be helpful if you could enlighten what I've missed. 

Best regards, 
David

**Comment by bangbingsyb** [comment]
@yrfu  Thanks for being interested in IIS Compression and letting us know the issue you hit. We are still working on the release notes and will update the readme in the repo.

The "Compression Scheme Prioritization" section of this article should explain your question:
https://docs.microsoft.com/en-us/iis/extensions/iis-compression/using-iis-compression

If you just want to enable brotli compression, you can deregister iiszlib.dll or gzip.dll in applicationHost.config. On the other hand, to support both brotli and gzip, but prioritize brotli, merely installing the two compression scheme providers is not sufficient. Since the compression scheme selection logic is built in the IIS static and dynamic compression modules shipped with Windows, obtaining the new compression scheme prioritization feature requires the latest IIS/Windows. For down-level IIS, you might still need URL Rewrite to help manipulate the "Accept-Encoding" request header to support both schemes.

**Comment by yrfu** [comment]
@bangbingsyb, noted and thanks for clarifying.
