### ISSUE TITLE
New release has version nr lower that the previous

### ISSUE THREAD

**Issue by RvdHout** [microsoft/IIS.Compression#34]
Previous version was version numbered as being: iiscompression_amd64.msi (v1.0.9)
New version is version numbered as iiscompression_amd64.msi (1.0.03219)

This is confusing :-/

**Comment by bangbingsyb** [comment]
@RvdHout Thanks for raising the issue. Is there any practical problem you hit for the new version (e.g. upgrade from the previous release)?

Note that the version format is defined as: major version (1) + minor version (0) + build number (03219). So the new release has the same major/minor version number as the previous release but with a higher build number. The build number does not have any particular meaning as long as it is incremental - otherwise you won't be able to install it if a previous version has been installed. We happened to change the build system that uses a different algorithm for calculating the build number.

**Comment by RvdHout** [comment]
No, no problems whatsoever...

I have this installed on multiple servers and went looking what version was actually currentlyinstalled, although i understand your explanation it would be clearer for novice users the new build would be higher

**Comment by bangbingsyb** [comment]
> No, no problems whatsoever...
> 
> I have this installed on multiple servers and went looking what version was actually currently installed, although i understand your explanation it would be clearer for novice users the when new build would be higher, now it looks lower

@RvdHout isn't 03219 higher than 9 :), or do I miss something here? If the build number is lower than the previous version, in-place upgrade will actually fail since the installer checks the version condition as a prerequisite for the installation.

**Comment by bangbingsyb** [comment]
Close the issue since it new version number does not cause any usability issue.
